typography_spectrum: 0.9023012728430331
color:
  brandStrength: 0.4907306609675288
  lightness: 0.9777367350179702
  saturation: 0.4656882989220321
  rhythmicContrast: 0.5331877309363335
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.21181257464922965
name: SourcePile
navigation:
  - name: My case studies.
    url: ericvanfossen.com
    type: external
title: The next best thing.
description: The expected is what we learned yesterday.
